spring:
  profiles:
    active: development

---
spring:
  profiles: development
  datasource:
    url: jdbc:postgresql://localhost:5432/dev_db
    username: dev_user
    password: dev_password

---
spring:
  profiles: test
  datasource:
    url: jdbc:postgresql://localhost:5433/test_db
    username: test_user
    password: test_password

